### ISSUE TITLE
Hetzner installation with ubuntu.sh

### ISSUE THREAD

**Issue by pierangelo1982** [nuvolaris/nuvolaris-documentation#4]
I tried to follow the guidelines, but when i launch this script:
```
curl -s https://www.nuvolaris.io/scripts/ubuntu.sh | bash
```
i get this error:
```
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
```
Seems that the file ubuntu.sh is not present on the current url of the project!

**Comment by msciabarra** [comment]
thanks it is a side effect of the latest update of the website

**Comment by msciabarra** [comment]
will solve asap

**Comment by msciabarra** [comment]
Fixed
